import type {
  User,
  Topic,
  StudySession,
  ActivityItem,
  Notification,
  WeeklyHours,
  ConfidenceDataPoint,
  ChartData,
  ProgressData,
  ExtractedTopics,
  UploadedFile,
} from "@/types";
import { EXAM_DATE } from "./constants";

export const dummyUser: User = {
  id: "user-1",
  name: "Alex Thompson",
  email: "alex.thompson@example.com",
  avatar: "",
  examDate: EXAM_DATE,
  studyHoursPerDay: 4,
  theme: "light",
  emailNotifications: true,
  reminderTime: "09:00",
  createdAt: new Date("2025-01-15"),
};

export const dummyTopics: Topic[] = [
  {
    id: "t1",
    name: "Introduction to Calculus",
    subject: "Mathematics",
    difficulty: "medium",
    status: "completed",
    confidence: "high",
    estimatedMinutes: 90,
    actualMinutes: 85,
    dueDate: "2025-05-10",
    completedDate: "2025-05-10",
    color: "#10B981",
    notes: "Understood limits and continuity thoroughly.",
  },
  {
    id: "t2",
    name: "Derivatives & Applications",
    subject: "Mathematics",
    difficulty: "hard",
    status: "completed",
    confidence: "medium",
    estimatedMinutes: 120,
    actualMinutes: 130,
    dueDate: "2025-05-12",
    completedDate: "2025-05-12",
    color: "#3B82F6",
  },
  {
    id: "t3",
    name: "Integration Techniques",
    subject: "Mathematics",
    difficulty: "hard",
    status: "studying",
    confidence: "low",
    estimatedMinutes: 150,
    actualMinutes: 80,
    dueDate: "2025-05-15",
    color: "#F59E0B",
  },
  {
    id: "t4",
    name: "Newton's Laws of Motion",
    subject: "Physics",
    difficulty: "medium",
    status: "completed",
    confidence: "high",
    estimatedMinutes: 100,
    actualMinutes: 95,
    dueDate: "2025-05-11",
    completedDate: "2025-05-11",
    color: "#10B981",
  },
  {
    id: "t5",
    name: "Thermodynamics",
    subject: "Physics",
    difficulty: "hard",
    status: "new",
    confidence: "low",
    estimatedMinutes: 130,
    actualMinutes: 0,
    dueDate: "2025-05-18",
    color: "#3B82F6",
  },
  {
    id: "t6",
    name: "Organic Chemistry Basics",
    subject: "Chemistry",
    difficulty: "medium",
    status: "revised",
    confidence: "high",
    estimatedMinutes: 90,
    actualMinutes: 90,
    dueDate: "2025-05-14",
    completedDate: "2025-05-13",
    color: "#8B5CF6",
  },
  {
    id: "t7",
    name: "Chemical Bonding",
    subject: "Chemistry",
    difficulty: "medium",
    status: "completed",
    confidence: "high",
    estimatedMinutes: 100,
    actualMinutes: 95,
    dueDate: "2025-05-09",
    completedDate: "2025-05-09",
    color: "#10B981",
  },
  {
    id: "t8",
    name: "Cell Biology",
    subject: "Biology",
    difficulty: "easy",
    status: "missed",
    confidence: "low",
    estimatedMinutes: 80,
    actualMinutes: 0,
    dueDate: "2025-05-13",
    color: "#EF4444",
  },
  {
    id: "t9",
    name: "Genetics & Evolution",
    subject: "Biology",
    difficulty: "hard",
    status: "new",
    confidence: "low",
    estimatedMinutes: 120,
    actualMinutes: 0,
    dueDate: "2025-05-20",
    color: "#3B82F6",
  },
  {
    id: "t10",
    name: "Electromagnetism",
    subject: "Physics",
    difficulty: "hard",
    status: "studying",
    confidence: "medium",
    estimatedMinutes: 140,
    actualMinutes: 60,
    dueDate: "2025-05-16",
    color: "#F59E0B",
  },
  {
    id: "t11",
    name: "Quantum Mechanics Intro",
    subject: "Physics",
    difficulty: "hard",
    status: "new",
    confidence: "low",
    estimatedMinutes: 110,
    actualMinutes: 0,
    dueDate: "2025-05-22",
    color: "#3B82F6",
  },
  {
    id: "t12",
    name: "Periodic Table & Properties",
    subject: "Chemistry",
    difficulty: "easy",
    status: "revised",
    confidence: "high",
    estimatedMinutes: 70,
    actualMinutes: 65,
    dueDate: "2025-05-14",
    completedDate: "2025-05-12",
    color: "#8B5CF6",
  },
];

export const dummySessions: StudySession[] = [
  {
    id: "s1",
    topicId: "t1",
    topicName: "Introduction to Calculus",
    date: "2025-05-10",
    startTime: "09:00",
    endTime: "10:25",
    duration: 85,
    confidence: "high",
    completed: true,
    notes: "Solid understanding of limits, derivatives basics.",
  },
  {
    id: "s2",
    topicId: "t2",
    topicName: "Derivatives & Applications",
    date: "2025-05-12",
    startTime: "10:00",
    endTime: "12:10",
    duration: 130,
    confidence: "medium",
    completed: true,
    notes: "Chain rule and implicit differentiation need more practice.",
  },
  {
    id: "s3",
    topicId: "t4",
    topicName: "Newton's Laws of Motion",
    date: "2025-05-11",
    startTime: "14:00",
    endTime: "15:35",
    duration: 95,
    confidence: "high",
    completed: true,
  },
  {
    id: "s4",
    topicId: "t7",
    topicName: "Chemical Bonding",
    date: "2025-05-09",
    startTime: "11:00",
    endTime: "12:35",
    duration: 95,
    confidence: "high",
    completed: true,
  },
  {
    id: "s5",
    topicId: "t3",
    topicName: "Integration Techniques",
    date: "2025-05-15",
    startTime: "09:00",
    endTime: "10:20",
    duration: 80,
    confidence: "low",
    completed: false,
    notes: "Integration by parts is confusing. Need more practice.",
  },
  {
    id: "s6",
    topicId: "t10",
    topicName: "Electromagnetism",
    date: "2025-05-16",
    startTime: "15:00",
    endTime: "16:00",
    duration: 60,
    confidence: "medium",
    completed: false,
  },
  {
    id: "s7",
    topicId: "t6",
    topicName: "Organic Chemistry Basics",
    date: "2025-05-13",
    startTime: "10:00",
    endTime: "11:30",
    duration: 90,
    confidence: "high",
    completed: true,
  },
  {
    id: "s8",
    topicId: "t12",
    topicName: "Periodic Table & Properties",
    date: "2025-05-12",
    startTime: "16:00",
    endTime: "17:05",
    duration: 65,
    confidence: "high",
    completed: true,
  },
];

export const dummyActivity: ActivityItem[] = [
  {
    id: "a1",
    type: "session",
    title: "Completed: Integration Techniques",
    description: "Studied for 80 minutes. Confidence: Low",
    timestamp: new Date().toISOString(),
    color: "#F59E0B",
  },
  {
    id: "a2",
    type: "achievement",
    title: "5-Day Study Streak! 🔥",
    description: "You've studied for 5 consecutive days. Keep it up!",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    color: "#10B981",
  },
  {
    id: "a3",
    type: "revision",
    title: "Revision Scheduled: Chemical Bonding",
    description: "Review session scheduled for tomorrow",
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    color: "#8B5CF6",
  },
  {
    id: "a4",
    type: "session",
    title: "Completed: Organic Chemistry Basics",
    description: "Studied for 90 minutes. Confidence: High",
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    color: "#10B981",
  },
  {
    id: "a5",
    type: "topic",
    title: "New Topic Added: Electromagnetism",
    description: "Physics topic added to your study plan",
    timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
    color: "#3B82F6",
  },
  {
    id: "a6",
    type: "reminder",
    title: "Study Reminder: Cell Biology",
    description: "You missed your scheduled session. Rescheduling...",
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    color: "#EF4444",
  },
];

export const dummyNotifications: Notification[] = [
  {
    id: "n1",
    type: "reminder",
    title: "Study Time!",
    message: "Your session on 'Integration Techniques' starts in 30 minutes.",
    timestamp: new Date().toISOString(),
    read: false,
    actionUrl: "/study",
  },
  {
    id: "n2",
    type: "revision",
    title: "Revision Due",
    message: "Time to revise 'Chemical Bonding' - last studied 5 days ago.",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: false,
    actionUrl: "/calendar",
  },
  {
    id: "n3",
    type: "missed",
    title: "Missed Session",
    message: "You missed 'Cell Biology' yesterday. New session has been scheduled.",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    read: false,
    actionUrl: "/dashboard",
  },
  {
    id: "n4",
    type: "exam",
    title: "Exam Countdown",
    message: "Only 95 days until your exam! You've completed 56% of your syllabus.",
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    read: true,
    actionUrl: "/analytics",
  },
  {
    id: "n5",
    type: "achievement",
    title: "Milestone Unlocked",
    message: "You've completed 25 study sessions! You're on fire! 🔥",
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    read: true,
  },
  {
    id: "n6",
    type: "reminder",
    title: "Weekly Goal Update",
    message: "You're at 80% of your weekly study goal. 2 more hours to go!",
    timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
    read: true,
  },
];

export const dummyWeeklyHours: WeeklyHours[] = [
  { day: "Mon", hours: 3.5, target: 4 },
  { day: "Tue", hours: 4, target: 4 },
  { day: "Wed", hours: 2.5, target: 4 },
  { day: "Thu", hours: 4.5, target: 4 },
  { day: "Fri", hours: 3, target: 4 },
  { day: "Sat", hours: 5, target: 4 },
  { day: "Sun", hours: 2, target: 4 },
];

export const dummyConfidenceTrend: ConfidenceDataPoint[] = [
  { date: "May 5", score: 45 },
  { date: "May 6", score: 50 },
  { date: "May 7", score: 48 },
  { date: "May 8", score: 55 },
  { date: "May 9", score: 62 },
  { date: "May 10", score: 68 },
  { date: "May 11", score: 65 },
  { date: "May 12", score: 72 },
  { date: "May 13", score: 78 },
  { date: "May 14", score: 75 },
  { date: "May 15", score: 80 },
  { date: "May 16", score: 82 },
];

export const dummyProgress: ProgressData = {
  totalTopics: 48,
  completedTopics: 27,
  remainingTopics: 21,
  completionPercent: 56.25,
  studyStreak: 5,
  masteryScore: 72,
};

export const dummyChartData: ChartData = {
  weeklyHours: dummyWeeklyHours,
  confidenceTrend: dummyConfidenceTrend,
  progress: dummyProgress,
  topicDistribution: [
    { name: "Completed", value: 27, color: "#10B981" },
    { name: "Studying", value: 5, color: "#F59E0B" },
    { name: "New", value: 11, color: "#3B82F6" },
    { name: "Missed", value: 5, color: "#EF4444" },
  ],
  subjectHours: [
    { subject: "Mathematics", hours: 28, color: "#2563EB" },
    { subject: "Physics", hours: 22, color: "#4F46E5" },
    { subject: "Chemistry", hours: 18, color: "#10B981" },
    { subject: "Biology", hours: 12, color: "#F59E0B" },
  ],
  monthlyActivity: [
    { month: "Jan", sessions: 8, hours: 12 },
    { month: "Feb", sessions: 12, hours: 18 },
    { month: "Mar", sessions: 15, hours: 24 },
    { month: "Apr", sessions: 20, hours: 32 },
    { month: "May", sessions: 18, hours: 28 },
    { month: "Jun", sessions: 22, hours: 35 },
  ],
};

export const dummyUploadedFiles: UploadedFile[] = [
  {
    id: "f1",
    name: "Semester_2_Syllabus.pdf",
    size: 2450000,
    type: "application/pdf",
    uploadProgress: 100,
    uploadedAt: new Date("2025-05-01"),
  },
  {
    id: "f2",
    name: "Physics_Notes.docx",
    size: 1200000,
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    uploadProgress: 100,
    uploadedAt: new Date("2025-04-28"),
  },
];

export const dummyExtractedTopics: ExtractedTopics = {
  fileId: "f1",
  fileName: "Semester_2_Syllabus.pdf",
  topics: dummyTopics.slice(0, 8),
  totalEstimatedHours: 780,
};

